程序执行出错: 'int' object has no attribute 'numel'
Traceback (most recent call last):
  File "/root/autodl-tmp/smart_design/train.py", line 870, in <module>
    trainer.train()
  File "/root/autodl-tmp/smart_design/train.py", line 808, in train
    loss = model(**batch).loss
           ^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/smart_design/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/smart_design/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/smart_design/lib/python3.11/site-packages/torch/_compile.py", line 51, in inner
    return disable_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/smart_design/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 838, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/smart_design/lib/python3.11/site-packages/unsloth/models/llama.py", line 1339, in PeftModel_fast_forward
    return self.base_model(
           ^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/smart_design/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/smart_design/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/smart_design/lib/python3.11/site-packages/peft/tuners/tuners_utils.py", line 216, in forward
    return self.model.forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/smart_design/lib/python3.11/site-packages/unsloth/models/llama.py", line 1215, in _CausalLM_fast_forward
    loss = unsloth_fused_ce_loss(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/smart_design/lib/python3.11/site-packages/unsloth_zoo/fused_losses/cross_entropy_loss.py", line 361, in unsloth_fused_ce_loss
    return apply_autograd_function(UnslothFusedLoss, dict(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/smart_design/lib/python3.11/site-packages/unsloth_zoo/fused_losses/cross_entropy_loss.py", line 40, in apply_autograd_function
    return getattr(autograd, "apply")(*(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/smart_design/lib/python3.11/site-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/smart_design/lib/python3.11/site-packages/unsloth_zoo/fused_losses/cross_entropy_loss.py", line 181, in forward
    if divisor.numel() != 1: divisor = divisor.ravel()[0]
       ^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'numel'
